In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census
import gmaps
import csv

# Census & gmaps API Keys
from config import (api_key, gkey)
c = Census(api_key, year=2020)

# Configure gmaps
gmaps.configure(api_key=gkey)

# State FIPS codes
# This is where you're going to import the FIPS codes from States.csv
states_df = pd.read_csv('resources/States.csv')

In [2]:
#c_variablesLink = "http://api.census.gov/data/2020/acs/acs5/variables.json"
#variablesData = requests.get(c_variablesLink).json()
#variables_pd = pd.DataFrame(variablesData)
# print(variables_pd)
#variables_pd.to_csv('variabledata.csv')

In [3]:
census_data_pbr = c.acs5.get(("B02001_002E","B02001_003E","B02001_004E","B02001_005E","B02001_006E","B02001_007E",
                          "B02001_008E","B02001_009E","B02001_010E","B01003_001E"), {'for': 'state:*'})

# Convert to DataFrame
census_pd_pbr = pd.DataFrame(census_data_pbr)
# census_pd_pbr['populationTotal'] = census_pd_pbr["B01003_001E"]
# = census_pd_pbr.sum(axis=1, numeric_only=True)
# Column Reordering
census_pd_pbr = census_pd_pbr.rename(columns={"B02001_002E":"White alone",
                                      "B02001_003E":"Black or African American alone",
                                      "B02001_004E":"American Indian and Alaska Native alone",
                                      "B02001_005E":"Asian alone",
                                      "B02001_006E":"Native Hawaiian and Other Pacific Islander alone",
                                      "B02001_007E":"Some other race alone",
                                      "B02001_008E":"Two or more races",
                                      "B02001_009E":"Two races including Some other race",
                                      "B02001_010E":"Two races excluding Some other race, and three or more races",
                                      "state":"State",
                                      "B01003_001E": "Total Population"})

census_pd_pbr = census_pd_pbr[["State", "Total Population","White alone","Black or African American alone","American Indian and Alaska Native alone","Asian alone",
                       "Native Hawaiian and Other Pacific Islander alone","Some other race alone","Two or more races",
                       "Two races including Some other race","Two races excluding Some other race, and three or more races"]]

In [4]:
# census_pd_pbr.sum(axis=1, numeric_only=True)

In [5]:
census_pd_pbr.head()

,State,Total Population,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some other race alone,Two or more races,Two races including Some other race,"Two races excluding Some other race, and three or more races"
0,42,12794885.0,10155004.0,1419582.0,20798.0,449320.0,4268.0,312888.0,433025.0,129126.0,303899.0
1,06,39346023.0,22053721.0,2250962.0,311629.0,5834312.0,149636.0,5623747.0,3122016.0,1472235.0,1649781.0
2,54,1807426.0,1672255.0,64285.0,3146.0,14228.0,474.0,9278.0,43760.0,9399.0,34361.0
3,49,3151239.0,2682881.0,38059.0,33222.0,73190.0,29450.0,160786.0,133651.0,47171.0,86480.0
4,36,19514849.0,12160045.0,3002401.0,76535.0,1674216.0,9376.0,1670723.0,921553.0,400648.0,520905.0

In [6]:
# print(states_df.loc("code",0))

# print (states_df.query('Code" == "0"')["Abbreviation"])
# states_df.query('Code == 1')['Abbreviation']

# states_df

In [7]:
census_data_pbrZip = c.acs5.get(("B02001_002E","B02001_003E","B02001_004E","B02001_005E","B02001_006E","B02001_007E",
                          "B02001_008E","B02001_009E","B02001_010E"), {'for': 'zip code tabulation area:*'})
census_pd_pbrZip = pd.DataFrame(census_data_pbrZip)
census_pd_pbrZip['rowTotal'] = census_pd_pbrZip.sum(axis=1, numeric_only= True)

census_pd_pbrZip = census_pd_pbrZip.rename(columns={
                                      "B02001_002E":"White alone",
                                      "B02001_003E":"Black or African American alone",
                                      "B02001_004E":"American Indian and Alaska Native alone",
                                      "B02001_005E":"Asian alone",
                                      "B02001_006E":"Native Hawaiian and Other Pacific Islander alone",
                                      "B02001_007E":"Some other race alone",
                                      "B02001_008E":"Two or more races",
                                      "B02001_009E":"Two races including Some other race",
                                      "B02001_010E":"Two races excluding Some other race, and three or more races",
                                      "zip code tabulation area":"Zip Code",
                                      "rowTotal": "Total Responses"
                                      })

census_pd_pbrZip = census_pd_pbrZip[["Zip Code","Total Responses","White alone","Black or African American alone","American Indian and Alaska Native alone","Asian alone",
                       "Native Hawaiian and Other Pacific Islander alone","Some other race alone","Two or more races",
                       "Two races including Some other race","Two races excluding Some other race, and three or more races"]]

In [8]:
census_pd_pbrZip.sample(25, random_state=100)

,Zip Code,Total Responses,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some other race alone,Two or more races,Two races including Some other race,"Two races excluding Some other race, and three or more races"
25075,27502,44762.0,35151.0,2759.0,29.0,3235.0,109.0,645.0,1417.0,760.0,657.0
17616,80440,2663.0,2428.0,24.0,0.0,0.0,0.0,21.0,95.0,0.0,95.0
31910,99741,546.0,175.0,0.0,287.0,2.0,0.0,0.0,41.0,10.0,31.0
26955,02635,2826.0,2652.0,150.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0
33013,60188,42921.0,26939.0,2851.0,48.0,8244.0,12.0,1929.0,1449.0,644.0,805.0
5336,03301,34512.0,29345.0,969.0,320.0,1633.0,0.0,321.0,962.0,92.0,870.0
24328,21702,44386.0,28382.0,7406.0,186.0,1699.0,20.0,1379.0,2657.0,1401.0,1256.0
27651,60455,16678.0,13275.0,608.0,0.0,803.0,0.0,632.0,680.0,364.0,316.0
31409,46781,681.0,658.0,0.0,2.0,2.0,0.0,5.0,7.0,0.0,7.0
30066,79012,2169.0,2143.0,0.0,0.0,0.0,0.0,0.0,13.0,13.0,0.0
13706,18417,1031.0,989.0,0.0,0.0,2.0,0.0,6.0,17.0,0.0,17.0
3319,52327,3466.0,3442.0,0.0,0.0,0.0,0.0,2.0,11.0,0.0,11.0
19880,38341,2327.0,2222.0,36.0,0.0,0.0,0.0,19.0,25.0,4.0,21.0
3911,67260,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29280,46126,4761.0,4569.0,0.0,0.0,0.0,0.0,4.0,94.0,0.0,94.0
1678,08318,12586.0,11130.0,843.0,46.0,58.0,0.0,111.0,199.0,5.0,194.0
13960,36401,7934.0,2901.0,4935.0,20.0,10.0,0.0,0.0,34.0,0.0,34.0
27454,13040,2416.0,2294.0,7.0,10.0,0.0,0.0,13.0,46.0,0.0,46.0
25174,71266,1859.0,1594.0,218.0,6.0,0.0,0.0,41.0,0.0,0.0,0.0
6910,38869,432.0,314.0,114.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0
4700,70053,18009.0,8696.0,5353.0,55.0,247.0,10.0,1210.0,1219.0,921.0,298.0
2311,28018,4201.0,4116.0,57.0,14.0,4.0,0.0,0.0,5.0,0.0,5.0
29048,77460,43.0,43.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32253,64119,31261.0,24449.0,1661.0,236.0,536.0,259.0,498.0,1811.0,473.0,1338.0
6939,36312,6590.0,5094.0,1002.0,0.0,12.0,0.0,6.0,238.0,130.0,108.0

In [9]:
census_data_povGender_Zip = c.acs5.get(("B17003_004E","B17003_005E","B17003_006E","B17003_007E","B17003_009E","B17003_010E",
						  "B17003_011E","B17003_012E","B17003_015E","B17003_016E","B17003_017E","B17003_018E","B17003_020E",
						  "B17003_021E","B17003_022E","B17003_023E",), {"for": "zip code tabulation area:*"})
census_pd_povGender_Zip = pd.DataFrame(census_data_povGender_Zip)
census_pd_povGender_Zip['populationTotal'] = census_pd_povGender_Zip.sum(axis=1, numeric_only= True)
census_pd_povGender_Zip = census_pd_povGender_Zip.rename(columns={"B17003_004E":"Male Below Poverty: Less than high school graduate",
									"B17003_005E":"Male Below Poverty: High school graduate (includes equivalency)",
									"B17003_006E":"Male Below Poverty: Some college, associate's degree",
									"B17003_007E":"Male Below Poverty: Bachelor's degree or higher",
									"B17003_009E":"Female Below Poverty: Less than high school graduate",
									"B17003_010E":"Female Below Poverty: High school graduate (includes equivalency)",
									"B17003_011E":"Female Below Poverty: Some college, associate's degree",
									"B17003_012E":"Female Below Poverty: Bachelor's degree or higher",
									"B17003_015E":"Male Above Poverty: Less than high school graduate",
									"B17003_016E":"Male Above Poverty: High school graduate (includes equivalency)",
									"B17003_017E":"Male Above Poverty: Some college, associate's degree",
									"B17003_018E":"Male Above Poverty: Bachelor's degree or higher",
									"B17003_020E":"Female Above Poverty: Less than high school graduate",
									"B17003_021E":"Female Above Poverty: High school graduate (includes equivalency)",
									"B17003_022E":"Female Above Poverty: Some college, associate's degree",
									"B17003_023E":"Female Above Poverty: Bachelors degree or higher",
                                     "zip code tabulation area":"Zip Code",
                                     "populationTotal": "Total Responses" })

census_pd_povGender_Zip = census_pd_povGender_Zip[[
"Zip Code","Total Responses",
"Male Below Poverty: Less than high school graduate",
"Male Below Poverty: High school graduate (includes equivalency)",
"Male Below Poverty: Some college, associate's degree",
"Male Below Poverty: Bachelor's degree or higher",
"Female Below Poverty: Less than high school graduate",
"Female Below Poverty: High school graduate (includes equivalency)",
"Female Below Poverty: Some college, associate's degree",
"Female Below Poverty: Bachelor's degree or higher",
"Male Above Poverty: Less than high school graduate",
"Male Above Poverty: High school graduate (includes equivalency)",
"Male Above Poverty: Some college, associate's degree",
"Male Above Poverty: Bachelor's degree or higher",
"Female Above Poverty: Less than high school graduate",
"Female Above Poverty: High school graduate (includes equivalency)",
"Female Above Poverty: Some college, associate's degree",
"Female Above Poverty: Bachelors degree or higher"
]]


census_pd_povGender_Zip.sample(25, random_state=100)

,Zip Code,Total Population,Male Below Poverty: Less than high school graduate,Male Below Poverty: High school graduate (includes equivalency),"Male Below Poverty: Some college, associate's degree",Male Below Poverty: Bachelor's degree or higher,Female Below Poverty: Less than high school graduate,Female Below Poverty: High school graduate (includes equivalency),"Female Below Poverty: Some college, associate's degree",Female Below Poverty: Bachelor's degree or higher,Male Above Poverty: Less than high school graduate,Male Above Poverty: High school graduate (includes equivalency),"Male Above Poverty: Some college, associate's degree",Male Above Poverty: Bachelor's degree or higher,Female Above Poverty: Less than high school graduate,Female Above Poverty: High school graduate (includes equivalency),"Female Above Poverty: Some college, associate's degree",Female Above Poverty: Bachelors degree or higher
25075,27502,28004.0,0.0,53.0,47.0,233.0,96.0,67.0,153.0,153.0,408.0,1012.0,3053.0,8483.0,185.0,1579.0,3793.0,8689.0
17616,80440,1918.0,0.0,6.0,9.0,98.0,0.0,13.0,33.0,16.0,21.0,298.0,337.0,260.0,14.0,128.0,402.0,283.0
31910,99741,323.0,0.0,7.0,5.0,1.0,2.0,7.0,7.0,3.0,8.0,43.0,37.0,41.0,16.0,33.0,32.0,81.0
26955,02635,2197.0,0.0,13.0,0.0,11.0,5.0,14.0,24.0,59.0,19.0,67.0,192.0,635.0,10.0,119.0,400.0,629.0
33013,60188,28762.0,160.0,160.0,186.0,329.0,238.0,312.0,248.0,285.0,1058.0,2259.0,3794.0,5739.0,1019.0,3033.0,4396.0,5546.0
5336,03301,22386.0,189.0,315.0,166.0,180.0,280.0,300.0,355.0,204.0,607.0,2489.0,2337.0,4367.0,526.0,2115.0,3041.0,4915.0
24328,21702,28366.0,522.0,242.0,140.0,94.0,256.0,359.0,506.0,102.0,1100.0,2691.0,3881.0,5135.0,979.0,2704.0,3427.0,6228.0
27651,60455,10595.0,137.0,310.0,101.0,44.0,88.0,319.0,90.0,213.0,706.0,1926.0,1134.0,679.0,612.0,1548.0,1508.0,1180.0
31409,46781,470.0,0.0,3.0,13.0,3.0,1.0,6.0,1.0,0.0,5.0,137.0,82.0,15.0,6.0,94.0,80.0,24.0
30066,79012,1297.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,125.0,309.0,80.0,0.0,112.0,429.0,146.0
13706,18417,740.0,6.0,9.0,16.0,5.0,10.0,10.0,6.0,4.0,35.0,184.0,84.0,25.0,39.0,117.0,72.0,118.0
3319,52327,2432.0,0.0,54.0,2.0,3.0,6.0,51.0,24.0,35.0,31.0,593.0,252.0,198.0,9.0,476.0,312.0,386.0
19880,38341,1685.0,43.0,53.0,17.0,12.0,20.0,74.0,21.0,0.0,75.0,374.0,205.0,73.0,63.0,397.0,179.0,79.0
3911,67260,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29280,46126,3174.0,0.0,30.0,2.0,2.0,39.0,4.0,96.0,0.0,227.0,565.0,370.0,313.0,83.0,523.0,471.0,449.0
1678,08318,8642.0,48.0,151.0,94.0,64.0,14.0,227.0,28.0,14.0,348.0,1426.0,992.0,1012.0,239.0,1669.0,1154.0,1162.0
13960,36401,5492.0,46.0,99.0,10.0,76.0,125.0,329.0,133.0,0.0,288.0,1218.0,400.0,320.0,235.0,1006.0,923.0,284.0
27454,13040,1729.0,14.0,39.0,12.0,0.0,25.0,39.0,30.0,2.0,135.0,334.0,261.0,113.0,34.0,281.0,269.0,141.0
25174,71266,1167.0,17.0,34.0,10.0,0.0,6.0,47.0,10.0,0.0,70.0,322.0,74.0,35.0,76.0,192.0,181.0,93.0
6910,38869,281.0,0.0,2.0,3.0,0.0,9.0,11.0,11.0,0.0,54.0,33.0,36.0,17.0,12.0,33.0,42.0,18.0
4700,70053,11741.0,545.0,239.0,185.0,41.0,578.0,238.0,232.0,70.0,825.0,1496.0,1182.0,1110.0,708.0,1020.0,2079.0,1193.0
2311,28018,3082.0,55.0,28.0,3.0,26.0,26.0,21.0,49.0,4.0,155.0,563.0,322.0,455.0,143.0,361.0,603.0,268.0
29048,77460,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0
32253,64119,20980.0,36.0,216.0,119.0,261.0,121.0,253.0,256.0,149.0,672.0,2777.0,3142.0,2770.0,550.0,3250.0,3202.0,3206.0
6939,36312,4452.0,66.0,92.0,27.0,2.0,56.0,160.0,83.0,21.0,285.0,664.0,620.0,323.0,191.0,668.0,868.0,326.0

In [ ]:
# census_pd_povGender_Zip.sample(25, random_state=100)

In [17]:
census_data_povRace = c.acs5.get(("B17001B_002E","B17001A_002E"), {"for": "zip code tabulation area:*"})
census_pd_povRace = pd.DataFrame(census_data_povRace)
census_pd_povRace = census_pd_povRace.rename(columns={"zip code tabulation area":"Zip Code",
                                                        "B17001B_002E":"Black respondants below poverty",
                                                       "B17001A_002E":"White respondants below poverty"})
census_pd_povRace.sample(25, random_state=100)

,Black respondants below poverty,White respondants below poverty,Zip Code
25075,422.0,1003.0,27502
17616,0.0,280.0,80440
31910,0.0,11.0,99741
26955,0.0,169.0,02635
33013,401.0,1377.0,60188
5336,142.0,2454.0,03301
24328,829.0,2515.0,21702
27651,37.0,2240.0,60455
31409,0.0,55.0,46781
30066,0.0,0.0,79012
13706,0.0,74.0,18417
3319,0.0,233.0,52327
19880,2.0,392.0,38341
3911,0.0,0.0,67260
29280,0.0,395.0,46126
1678,10.0,751.0,08318
13960,1186.0,400.0,36401
27454,7.0,195.0,13040
25174,181.0,123.0,71266
6910,100.0,16.0,38869
4700,1254.0,1086.0,70053
2311,41.0,277.0,28018
29048,0.0,0.0,77460
32253,20.0,2251.0,64119
6939,271.0,527.0,36312